# Generated by Django 4.2.19 on 2025-02-27 13:33

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENT', '0002_alter_books_description_alter_books_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
